# Generated by Django 2.2.2 on 2019-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
