# Generated by Django 2.2.2 on 2019-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
